./maya_experiment.sh canneal; 
./maya_experiment.sh freqmine; 
./maya_experiment.sh vips; 
./maya_experiment.sh streamcluster
./maya_experiment.sh blackscholes;
./maya_experiment.sh bodytrack;
./maya_experiment.sh splash2x.radiosity;
./maya_experiment.sh splash2x.volrend;
./maya_experiment.sh splash2x.water_nsquared;
./maya_experiment.sh splash2x.water_spatial